### ISSUE TITLE
Peer dependencies required to install `@tiptap-pro/extension-drag-handle-react` are not mentioned in the documentation

### ISSUE THREAD

**Issue by kart-c** [ueberdosis/tiptap-docs#23]
- At my current organization we are using a custom `drag-handle` extension. But since Tiptap has it's own official drag extension, we wanted to migrate to it.
- After installing `@tiptap-pro/extension-drag-handle-react` was further prompted to install it's required peer dependencies listed below.
  - `@tiptap-pro/extension-drag-handle`
  -  `@tiptap-pro/extension-node-range`
  - `@tiptap/extension-collaboration`
  - `y-prosemirror`
  - `yjs`
  - `y-protocols`
  
Since these peer dependencies are required for the `@tiptap-pro/extension-drag-handle-react`, I think it would be good to mention these in the documentation.

**Comment by kart-c** [comment]
Let me know, if I can open a PR for the same.

**Comment by nperez0111** [comment]
I'd appreciate a PR for this, thanks for letting us know @kart-c

**Comment by mertbuilds** [comment]
Hi, I was about to submit a PR about removing the following dependencies from `@tiptap-pro/extension-drag-handle-react`'s documentation.

`@tiptap-pro/extension-node-range`
`@tiptap/extension-collaboration`
`y-prosemirror`
`yjs`
`y-protocols`

Can someone explain why these are needed for `@tiptap-pro/extension-drag-handle-react`? `@tiptap-pro/extension-drag-handle` makes sense but I can't understand the relation with others.

I'm able to use the extension without the listed dependencies. Maybe things have changed since then and I'm happy to update the documentation.

**Update**: Turns out even `@tiptap-pro/extension-drag-handle` is not needed. `@tiptap-pro/extension-drag-handle-react` works by itself.
